theme: jekyll-theme-midnight
title: Welcome to JournalSource
Description: A Digital Bibliography of Resources on Journal Writing
email: journalique@aol.com
twitter_username: Incunabulus
github_username:  Gia-Alexander
baseurl: Research
url: http://gia-alexander/github.io/journalsource
